<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.codeturnery</groupId>
	<artifactId>common-java-project-pom</artifactId>
	<version>1.0.4</version>
	<packaging>pom</packaging>
	<name>Basic Java project POM</name>
	<description>Provides common Maven configuration for Java ${java.version} projects.</description>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>17</java.version>
		<junit.version>5.12.2</junit.version>
		<mockito.version>5.17.0</mockito.version>
		<slf4j.version>2.0.17</slf4j.version>
	</properties>

	<dependencies>
		<!-- NULL HANDLING -->
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.annotation</artifactId>
			<version>2.3.100</version>
		</dependency>

		<!-- JUNIT5 -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- MOCKING -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- LOGGING -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-ext</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>

			<!-- generate one documentation for developers with all docblocks and one for users with public docblocks only -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
					<reportOutputDirectory>${project.reporting.outputDirectory}</reportOutputDirectory>
				</configuration>
				<executions>
					<execution>
						<id>default-test</id>
						<configuration>
							<!-- skip default execution -->
							<skip>true</skip>
						</configuration>
					</execution>
					<execution>
						<id>attach-all-javadocs</id>
						<configuration>
							<!-- For most projects documenting every
							member and method is not feasable, so we
							silence "missing" warnings for the developer
							documentation. Warnings for the user
							documentation (i.e. public members and
							methods) will still be shown by the
							"attach-public-javadocs" configured below -->
							<doclint>all,-missing</doclint>
							<show>private</show>
							<outputDirectory>${project.reporting.outputDirectory}/dev-javadoc</outputDirectory>
						</configuration>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
					<execution>
						<id>attach-all-test-javadocs</id>
						<configuration>
							<!-- We assume that test documentation is only relevant for developers. Accordingly,
							we suppress any missing warning (i.e. for public and private members/methods)
							with the same reasoning as in attach-all-javadocs. -->
							<doclint>all,-missing</doclint>
							<show>private</show>
							<outputDirectory>${project.reporting.outputDirectory}/dev-test-javadoc</outputDirectory>
						</configuration>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
					<execution>
						<id>attach-public-javadocs</id>
						<configuration>
							<doclint>all</doclint>
							<show>public</show>
							<outputDirectory>${project.reporting.outputDirectory}/user-javadoc</outputDirectory>
						</configuration>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>